カテゴリー管理画面作成
gizumo-inc/gizumo_wiki_lesson pull request #198
Opened 2023-05-17 06:08 UTC by saito1231

## チケットのリンク
https://gizumo.backlog.com/view/GIZFE-927

## やったこと
 - カテゴリを管理するための画面作成
 - API通信を通して、カレゴリ一覧情報を取得
 - カテゴリ管理画面のレイアウト
 - APIから取得したカテゴリ一覧が画面右側に表示される
 - 最新のものが一番上に来るように順番を変更する

## やらないこと
なし

## テスト
https://gizumo.backlog.com/view/GIZFE-929

## 特にレビューをお願いしたい箇所

全体を通して、もっと良い書き方があればアドバイス頂ければと思います。

2023-05-17 08:47 UTC, Joex13 reviewed
レビューしました。

2023-05-17 08:47 UTC, jj13jp commented on src/components/globals/Sidebar/index.stories.js
>    },
[must]
このファイルはプッシュ（コミット）しないでください！（今回の課題と関係のないファイルのため）

必要のないファイルはプッシュを避けることで、レビューの効率も上がるのでgoodです！

2023-05-17 08:47 UTC, Joex13 commented on src/components/pages/Categories/List.vue
> +    width: calc(100% - 65%);
[imo]
calcを使う必要はないと思います。
is-listも同様です。

2023-05-17 08:47 UTC, Joex13 commented on src/components/pages/Categories/List.vue
[ask]
APIから返されたエラーメッセージの表示機能が確認できませんでした！
ご確認をお願い致します！（自分のレビューミスでしたらごめんなさい！）

2023-05-17 08:58 UTC, Joex13 reviewed
コメントを一件追加

2023-05-17 08:58 UTC, Joex13 commented on src/js/_store/modules/categories.js
> +    categoryListLength: state => state.categoryList.Length,
[must]
不要な記述だと思います！（使われている様子がないため）

2023-05-18 02:13 UTC, Joex13 requested changes
レビューしました。

2023-05-18 02:13 UTC, Joex13 commented on src/components/molecules/CategoryList/index.vue
> +        {{ errorMessage }}
[must]
エラーメッセージはCategoryPostコンポーネントで実装をお願いします！（デフォルトである程度実装が用意されているため）

実装方法（propsの渡し方）はgoodです！

2023-05-18 02:19 UTC, Joex13 commented
[must]
以下二つのファイルをコミットから除外してください！（Files changedページに表示されないようにしてください！）

・[globals/Sidebar/index.stories.js](https://github.com/gizumo-education/gizumo_wiki_lesson/pull/198/files#diff-991f8a145aec919c871528fafac175c758da805d4f8f0f98537a2fd5f00f0ab4)
・[molecules/CategoryList/index.vue](https://github.com/gizumo-education/gizumo_wiki_lesson/pull/198/files#diff-b06e8249caa7f4a90c6f918b15a41f737c18e8ef837ae976984d8b0ef68d1ba2)

理由は、二つとも今回の課題とは関係のないファイルだからです！
gitの機能を使えば簡単に実現できますので、調査してみてください！

2023-05-18 03:27 UTC, Joex13 commented
gitには特定のファイルを別ブランチや別コミットからコピーする機能があります。
それを使うと除外も簡単だと思います。（他にも方法はありますけどね）

2023-05-18 03:30 UTC, Joex13 commented
[must]
もっとコミットの粒度を小さくしてください！
複数の修正をまとめてコミットしてしまうとレビュアーの負担が増してしまいます！
その際にコミットメッセージにも気を使えると更にgoodです！

2023-05-18 06:21 UTC, saito1231 commented on src/components/globals/Sidebar/index.stories.js
>    },
不要な変更を元に戻しました。

2023-05-18 06:22 UTC, saito1231 commented on src/components/pages/Categories/List.vue
> +    width: calc(100% - 65%);
calcを使用せずにwidthの値を記述しました。

2023-05-18 06:23 UTC, saito1231 commented on src/js/_store/modules/categories.js
> +    categoryListLength: state => state.categoryList.Length,
不要な記述gettersを削除しました。

2023-05-18 06:24 UTC, saito1231 commented on src/components/molecules/CategoryList/index.vue
> +        {{ errorMessage }}
categoryListコンポーネントに記述したエラーメッセージをCategoryPostコンポーネントで実装をおこないました。

2023-05-18 06:25 UTC, saito1231 commented
・[globals/Sidebar/index.stories.js]
・[molecules/CategoryList/index.vue]
の不要な記述を削除し除外するができました。

2023-05-18 07:21 UTC, Joex13 reviewed
レビューしました！

修正お願いしたところはすべてOKでした！

最後にレビュー漏れしていた部分の修正をお願いします！
あともう少しです！

2023-05-18 07:21 UTC, Joex13 commented on src/components/pages/Categories/List.vue
> +    border-left: solid 1px rgb(217, 216, 216);
[nits]
色の指定は変数を使いましょう！

変数は"src\styles\scss\_utils\ _variables.scss"に記載があります。

2023-05-18 07:21 UTC, Joex13 commented on src/js/_store/modules/categories.js
> +    categoryPost: [],
[nits]
不要な記述なので削除しましょう！

2023-05-18 07:21 UTC, Joex13 commented on src/components/pages/Categories/List.vue
[must]
ファイル名を変えましょう！

このファイルはPostとListの両方のmoleculesを含んでいるため、そのことを示すファイル名だと良いです。
List.vueだとListだけを読み込むコンポーネントなのかと勘違いさせてしまうので。

（自分も指摘されました・・・）

2023-05-18 07:26 UTC, saito1231 commented on src/components/pages/Categories/List.vue
> +    border-left: solid 1px rgb(217, 216, 216);
borderの色を$separator-colorを使うよう変更しました。

2023-05-18 07:28 UTC, saito1231 commented on src/js/_store/modules/categories.js
> +    categoryPost: [],
不要な記述categoryPost[]を削除しました。

2023-05-18 07:32 UTC, saito1231 commented on src/components/pages/Categories/List.vue
ファイル名をCategories.vueに変更いたしました。

2023-05-18 08:09 UTC, Joex13 reviewed
レビューしました！
これで本当に最後です。

2023-05-18 08:09 UTC, Joex13 commented on src/js/_store/modules/categories.js
> +    },
[nits]
使ってないので消してしまいましょう。

2023-05-18 08:12 UTC, saito1231 commented on src/js/_store/modules/categories.js
> +    },
不要なコードの削除を行いました。

2023-05-18 08:20 UTC, Joex13 approved these changes

2023-05-18 10:38 UTC, ryo-kihara commented on src/components/pages/Categories/Categories.vue
> +    :class="categoryObject"
[imo]

条件によってクラスが付与されるか否かというのは今回必要ないと思うので、そういった時はバインドさせる必要はなく、単純に以下のように記述することができます。

また、`is-〇〇` というふうにクラス名を設定してもらってると思いますが、`is` という単語はプログラミング界隈では、真偽値を表す時に使用されます。
上述した通り、今回は特に class を付与するということに対して条件はないので、単純に `category` などのクラス名で良いと思います。

他の箇所も同じような修正が必要そうなので修正の方お願いします。

```suggestion
    class="category"
```

2023-05-18 10:38 UTC, ryo-kihara commented on src/components/pages/Categories/Categories.vue
> +  mixins: [Mixins],
[ask]

mixins を定義した理由は何かありますか？
今回実装してもらう機能には、特に不要だと思うので特に理由がなければ削除してしまって良いと思いました。

2023-05-18 10:38 UTC, ryo-kihara commented on src/components/pages/Categories/Categories.vue
> +<style lang="scss" scoped>
[challenge]

`scoped` にはどんな役割があるでしょう？

2023-05-18 10:38 UTC, ryo-kihara commented on src/js/_store/modules/categories.js
> +  namespaced: true,
[challenge]

`namespaced: true` にはどんな役割がありますか？

2023-05-18 10:38 UTC, ryo-kihara commented on src/js/_store/modules/categories.js
> +    getAllCategories({ commit, rootGetters }) {
[challenge]

`rootGetters` では何が取得できますか？

2023-05-18 10:38 UTC, ryo-kihara commented on src/js/_store/modules/categories.js
> +        commit('doneGetAllCategories', categoryList);
[nits]

一時変数は逆に可読性を落とします。
1度しか使わないのであれば直接指定した方が読みやすいかなと思います。

```suggestion
        commit('doneGetAllCategories', data.categories);
```

2023-05-18 11:46 UTC, saito1231 commented on src/components/pages/Categories/Categories.vue
> +    :class="categoryObject"
通常の記述方法でclassを記述しました。

2023-05-18 11:48 UTC, saito1231 commented on src/components/pages/Categories/Categories.vue
> +  mixins: [Mixins],
機能確認し不必要だった為、mixinsを削除しました。

2023-05-18 11:51 UTC, saito1231 commented on src/components/pages/Categories/Categories.vue
> +<style lang="scss" scoped>
scopedを使用するとコンポーネントごとにCSSを分離し、互いに影響しないようにすることができます。またコンポーネント内で定義されたスタイルが他のコンポーネントに影響を与えず、互いに独立して適用されるようになります。コンポーネント単位での再利用性や保守性を向上させるのに役立ち、グローバルスコープでのセレクタ衝突やスタイルの競合を防ぐことができます。

2023-05-18 11:55 UTC, saito1231 commented on src/js/_store/modules/categories.js
> +        commit('doneGetAllCategories', categoryList);
categoryListを定義して代入せず、直接してしました。

2023-05-18 11:58 UTC, saito1231 commented on src/js/_store/modules/categories.js
> +  namespaced: true,
大規模なアプリケーションの状態管理を容易にするために、ストアをモジュールに分割することができます。各モジュールは、自身の状態、アクション、ミューテーション、ゲッターを持つことができます。ネームスペースを有効にすると、モジュール内のアクション、ミューテーション、ゲッターがネームスペースによって区別されてこれにより、異なるモジュール間で同じ名前のアクションやミューテーションを定義することができ、名前の衝突を回避することができます。

2023-05-18 12:01 UTC, saito1231 commented on src/js/_store/modules/categories.js
> +    getAllCategories({ commit, rootGetters }) {
ルートのゲッターである[auth/token]を参照しており、APIリクエストに必要な認証トークンを取得している。今回のリクエストは認証トークンがないとリクエストできない。

2023-05-19 01:36 UTC, ryo-kihara commented on src/components/pages/Categories/Categories.vue
> +    class="categoryObject"
[imo]

オブジェクトではなくなったので、`Object` という単語を class 名に付与しなくて良くなったかと思います。
単純に `category` とかで良いかと思います。

2023-05-19 01:36 UTC, ryo-kihara commented on src/components/pages/Categories/Categories.vue
> +      class="categoryPost"
[imo]

以下のようにした方が、Sass で表現した時に可読性が上がると思います。
また、他のファイルの記述を見ても以下のようにケバブケースになっていそうなので修正をお願いします。

```suggestion
      class="category-post"
```

2023-05-19 01:40 UTC, saito1231 commented on src/components/pages/Categories/Categories.vue
> +    class="categoryObject"
class名を「categoryObject」から「category」に変更しました。

2023-05-19 01:45 UTC, saito1231 commented on src/components/pages/Categories/Categories.vue
> +      class="categoryPost"
class名をキャメルケースからケバブケースの記述に変更しました。

2023-05-19 02:06 UTC, ryo-kihara commented on src/components/pages/Categories/Categories.vue
> +  // width: 100%;
[nits]

コメントアウトは削除しておきましょう。
ちなみにもしコメントアウトを残しておきたい場合は、理由も一緒に記述しておくと良いかなと思います

```suggestion
```

2023-05-19 02:09 UTC, saito1231 commented on src/components/pages/Categories/Categories.vue
> +  // width: 100%;
すいません見落としていました。
コメントアウトを削除しました。

2023-05-19 02:26 UTC, merged