Feature/gizfe 502
gizumo-inc/gizumo_wiki_lesson pull request #81
Opened 2022-11-10 03:54 UTC by kosuke-codeman3

[チケットのリンク](https://gizumo.backlog.com/view/GIZFE-502)

作業内容（今回やったこと）
-カテゴリー管理画面作成
-カテゴリー管理画面へのリンク追加

動作確認
・カテゴリー一覧が降順で表示されていること
・サイドバーの「カテゴリー」をクリックするとカテゴリー管理画面に遷移すること
・カテゴリー管理画面の「カテゴリー名入力ボックス」に文字入力できること
・カテゴリー管理画面に遷移した際、「カテゴリー名入力ボックス」が空欄であること
・カテゴリー管理画面で「このカテゴリーの記事リンク」を押下した際、該当カテゴリーの記事一覧のURLが設定されること
・カテゴリー管理画面の更新ボタンを押下した際、押下したカテゴリーの詳細・編集画面のURLが設定されること

2022-11-10 06:54 UTC, XeicuLy requested changes
コメントしたので、確認お願いします！

2022-11-10 06:54 UTC, XeicuLy commented on src/js/_store/modules/categories.js
> +    category: {},
stateで管理する`category`は複数あると思うので、`categoryList`とかの方が分かりやすいかなと思いました！

2022-11-10 06:54 UTC, XeicuLy commented on src/js/_store/modules/categories.js
> +        commit('doneGetAllCategories', payload);
payloadに定数として代入するのも良いかもしれませんが、引数にそのまま`res.data.categories.reverse()`を渡してあげるのも手なのではないかと思います。

2022-11-10 06:54 UTC, XeicuLy commented on src/js/_store/modules/categories.js
> +    },
引数の渡し方を変更すれば、ここの記述はもう少しシンプルになると思います！

2022-11-10 06:54 UTC, XeicuLy commented on src/components/molecules/CategoryList/index.vue
> +      default: () => ({}),
ここの書き換えは必要でしたか？

2022-11-10 06:54 UTC, XeicuLy commented on src/components/pages/Categories/index.vue
>  <template>
articleを参考に、新しくコンポーネントを作ったほうがいいと思いました！

2022-11-10 09:49 UTC, kosuke-codeman3 commented on src/js/_store/modules/categories.js
> +    category: {},
カテゴリー内でのcategoryの表記をcategoryListに修正しました。

2022-11-10 09:50 UTC, kosuke-codeman3 commented on src/js/_store/modules/categories.js
> +    },
state.categoryに直接payload.categoryのデータを格納するように修正しました。

2022-11-10 09:53 UTC, kosuke-codeman3 commented on src/components/molecules/CategoryList/index.vue
> +      default: () => ({}),
categoryListに渡しているcategoriesの型を配列型に変更したため、書き換え前の状態に戻しました。

2022-11-10 09:57 UTC, kosuke-codeman3 commented on src/components/pages/Categories/index.vue
>  <template>
index.vueの内容をarticleのコンポーネントと同じに修正し、今まで作っていたindex.vueはList.vueにリネームしました。
articleと同じようにrouterでカテゴリーの各コンポーネント呼び出す形に修正しました。

2022-11-11 02:29 UTC, XeicuLy reviewed
再度コメントしたので、確認をお願いします！

2022-11-11 02:29 UTC, XeicuLy commented on src/components/pages/Categories/List.vue
> +    },
ここは直接`state`の`categoryList`を`return`してあげれば処理が1行になって良いんじゃないかと思いました！

2022-11-11 02:29 UTC, XeicuLy commented on src/js/_store/modules/categories.js
> +      axios(rootGetters['auth/token'])({
わかりやすくていいですが、コメントアウトをPRに出すことは控えるようにしましょう！

2022-11-11 02:29 UTC, XeicuLy commented on src/components/pages/Categories/List.vue
> +  display:flex;
大変細かくて申し訳有りませんが、`display:flex;`ではなく`display: flex;`と、スペースをあけましょう！

2022-11-11 02:29 UTC, XeicuLy commented on src/components/pages/Categories/List.vue
> +  border-left:solid 1px $separator-color;
こちらも上記同様スペースをあけましょう！

2022-11-11 03:14 UTC, kosuke-codeman3 commented on src/js/_store/modules/categories.js
> +      axios(rootGetters['auth/token'])({
コメントを削除しました

2022-11-11 03:14 UTC, kosuke-codeman3 commented on src/components/pages/Categories/List.vue
> +  display:flex;
[display: flex;]表記に修正しました

2022-11-11 03:15 UTC, kosuke-codeman3 commented on src/components/pages/Categories/List.vue
> +  border-left:solid 1px $separator-color;
[border-left: solid 1px $separator-color;]の表記に修正しました

2022-11-11 03:34 UTC, kosuke-codeman3 commented on src/components/pages/Categories/List.vue
> +    },
`return this.$store.state.categories.categoryList;`で値を返すように修正しました。

2022-11-11 05:31 UTC, XeicuLy reviewed
再度コメントさせていただいたので、確認お願いします！

2022-11-11 05:31 UTC, XeicuLy commented on src/js/_store/modules/categories.js
> +        commit('doneGetAllCategories', payload);
わざわざ`payload`にobjectで格納しなくても良いのではないかと思います！

例えば、
```suggestion
      }).then(res => {
        commit('doneGetAllCategories', res.data.categories.reverse());
```
もしくは、
```suggestion
      }).then(res => {
        const categoryListData = res.data.categories.reverse();
        commit('doneGetAllCategories', categoryListData);
```
というようにしてあげると、`doneGetAllCategories`で代入するものはpayloadだけ、とシンプルになるのでは無いかと思いました！

2022-11-11 08:00 UTC, kosuke-codeman3 commented on src/js/_store/modules/categories.js
> +        commit('doneGetAllCategories', payload);
ありがとうございます。
1つ目の修正案のやり方で修正しました。

95e5318e1b6af8360a58eee11ed4e45f06656396

APIから受け取る配列は一つだけなので、わざわざpayloadに入れる必要はないんですね。

2022-11-11 08:52 UTC, XeicuLy approved these changes

2022-11-11 09:42 UTC, ky1031 reviewed
コメントしました

2022-11-11 09:42 UTC, ky1031 commented on src/components/pages/Categories/List.vue
> +      <app-category-post
[nits] `class="category-post"`は`app-category-post`に含めてあげれば無駄なタグを減らせます

2022-11-11 09:42 UTC, ky1031 commented on src/components/pages/Categories/List.vue
> +      <app-category-list
[nits] `class="category-list"`も`app-category-list`に含めて無駄なタグが減らせます

2022-11-14 00:54 UTC, kosuke-codeman3 commented on src/components/pages/Categories/List.vue
> +      <app-category-post
section内のclassをapp-category-postタグのclassに追加し、sectionタグは不必要なため削除しました。

7e43816d9997c70729ef7db63aeb65a8731c356f

2022-11-14 00:55 UTC, kosuke-codeman3 commented on src/components/pages/Categories/List.vue
> +      <app-category-list
section内のclassをapp-category-postタグのclassに追加し、sectionタグは不必要なため削除しました。

7e43816d9997c70729ef7db63aeb65a8731c356f

2022-11-14 01:58 UTC, merged